### ISSUE TITLE
Map how pages are connected / relate to each other

### ISSUE THREAD

**Issue by timothynorman** [algonquin-college-sat/24s-cst8319-310-team3#85]
Map how pages on the portal are connected to each other to help us create wireframes, backend code, etc.

**Comment by andresporrasdev** [comment]
`<div style="width: 960px; height: 720px; margin: 10px; position: relative;"><iframe allowfullscreen frameborder="0" style="width:960px; height:720px" src="https://lucid.app/documents/embedded/b76b29d8-fdc0-46c8-b779-194826766b91" id="AGAMXEGEMu-F"></iframe></div>`
